import type { GraphicDevice } from "./types";

/**
 * The graphic device taxonomy (doctrine §2–§4, §6).
 *
 * A fixed, curated set — the same posture as engine/prompt/render/vocabulary.ts
 * and engine/dkv/doctrine.ts: reviewable in one file, not generated per recipe.
 * Every device declares a real movement/industry/objective compatibility set
 * (data/movements, data/industries, types/schemas/brief.schema.ts) rather than
 * an invented one, and every device carries at least one purpose from
 * GraphicDevicePurpose — "looks cool" is not a representable value.
 *
 * Movement and industry ids referenced here are exactly the ids shipped in
 * data/movements and data/industries. Adding a movement or industry file
 * later does not require touching this file: an empty compatibility array
 * already means "no restriction", and a new id simply does not match any
 * device's list until this taxonomy is deliberately extended for it.
 */
export const GRAPHIC_DEVICES: readonly GraphicDevice[] = [
  // --- Structural devices (doctrine §3.A) -----------------------------------
  {
    id: "modular-grid-blocks",
    category: "structural",
    name: "Modular grid blocks",
    purpose: ["hierarchy", "rhythm"],
    compatibleMovements: ["bauhaus", "swiss-international", "contemporary-digital"],
    compatibleIndustries: [],
    incompatibleIndustries: [],
    suitableObjectives: [],
    minIntensity: "minimal",
    expressiveAudienceOnly: false,
    conflictsWithDenseCopy: false,
    reduceIfDenseImagery: false,
    requiresGrid: true,
    pairsWith: ["rule-divider", "column-system"],
    avoidWith: [],
    culturalNote: null,
    promptEn: "Divide the surface into modular grid blocks that carry the composition's structure.",
    promptId: "Bagi permukaan menjadi blok grid modular yang menopang struktur komposisi."
  },
  {
    id: "framing-border",
    category: "structural",
    name: "Framing border",
    purpose: ["framing", "emphasis"],
    compatibleMovements: ["editorial-modernism", "minimalism", "swiss-international"],
    compatibleIndustries: [],
    incompatibleIndustries: [],
    suitableObjectives: [],
    minIntensity: "minimal",
    expressiveAudienceOnly: false,
    conflictsWithDenseCopy: false,
    reduceIfDenseImagery: false,
    requiresGrid: false,
    pairsWith: [],
    avoidWith: [],
    culturalNote: null,
    promptEn: "Add a restrained framing border that holds the composition inside a single, deliberate edge.",
    promptId: "Tambahkan garis bingkai (framing border) yang tegas dan menahan komposisi dalam satu tepi yang disengaja."
  },
  {
    id: "rule-divider",
    category: "structural",
    name: "Rule / divider line",
    purpose: ["hierarchy", "information_grouping"],
    compatibleMovements: ["swiss-international", "editorial-modernism", "minimalism", "bauhaus"],
    compatibleIndustries: [],
    incompatibleIndustries: [],
    suitableObjectives: [],
    minIntensity: "minimal",
    expressiveAudienceOnly: false,
    conflictsWithDenseCopy: false,
    reduceIfDenseImagery: false,
    requiresGrid: false,
    pairsWith: ["modular-grid-blocks", "label-tag"],
    avoidWith: [],
    culturalNote: null,
    promptEn: "Use a single rule line to separate zones and make the reading order explicit.",
    promptId: "Gunakan satu garis pembatas (rule) untuk memisahkan zona dan menegaskan urutan baca."
  },
  {
    id: "modular-panel",
    category: "structural",
    name: "Modular panel",
    purpose: ["information_grouping", "hierarchy"],
    compatibleMovements: ["bauhaus", "swiss-international", "contemporary-digital"],
    compatibleIndustries: [],
    incompatibleIndustries: [],
    suitableObjectives: [],
    minIntensity: "moderate",
    expressiveAudienceOnly: false,
    conflictsWithDenseCopy: false,
    reduceIfDenseImagery: false,
    requiresGrid: true,
    pairsWith: ["modular-grid-blocks"],
    avoidWith: [],
    culturalNote: null,
    promptEn: "Contain supporting information inside one modular panel rather than scattering it across the frame.",
    promptId: "Kelompokkan informasi pendukung ke dalam satu panel modular, bukan tersebar di seluruh bidang."
  },
  {
    id: "cropped-image-window",
    category: "structural",
    name: "Cropped image window",
    purpose: ["framing", "image_integration"],
    compatibleMovements: ["editorial-modernism", "contemporary-digital", "brutalism"],
    compatibleIndustries: [],
    incompatibleIndustries: [],
    suitableObjectives: [],
    minIntensity: "moderate",
    expressiveAudienceOnly: false,
    conflictsWithDenseCopy: false,
    reduceIfDenseImagery: false,
    requiresGrid: false,
    pairsWith: ["selective-image-masking", "oversized-cropped-headline", "type-crossing-image-boundary"],
    avoidWith: [],
    culturalNote: null,
    promptEn: "Use a cropped image boundary that intersects the modular grid rather than sitting fully inside it.",
    promptId: "Gunakan batas crop gambar yang memotong grid modular, bukan diam sepenuhnya di dalamnya."
  },
  {
    id: "column-system",
    category: "structural",
    name: "Column system",
    purpose: ["hierarchy", "rhythm"],
    compatibleMovements: ["swiss-international", "editorial-modernism"],
    compatibleIndustries: [],
    incompatibleIndustries: [],
    suitableObjectives: [],
    minIntensity: "moderate",
    expressiveAudienceOnly: false,
    conflictsWithDenseCopy: false,
    reduceIfDenseImagery: false,
    requiresGrid: true,
    pairsWith: ["modular-grid-blocks", "stacked-typography-block"],
    avoidWith: [],
    culturalNote: null,
    promptEn: "Run a disciplined column system beneath the layout to keep every block aligned to the same rhythm.",
    promptId: "Gunakan sistem kolom yang disiplin di bawah layout agar setiap blok sejajar pada ritme yang sama."
  },

  // --- Expressive devices (doctrine §3.B) -----------------------------------
  {
    id: "geometric-block-accent",
    category: "expressive",
    name: "Controlled geometric block",
    purpose: ["emphasis", "contrast"],
    compatibleMovements: ["bauhaus", "contemporary-digital", "brutalism"],
    compatibleIndustries: [],
    incompatibleIndustries: [],
    suitableObjectives: [],
    minIntensity: "moderate",
    expressiveAudienceOnly: false,
    conflictsWithDenseCopy: false,
    reduceIfDenseImagery: false,
    requiresGrid: false,
    pairsWith: ["modular-grid-blocks"],
    avoidWith: ["organic-blob-accent"],
    culturalNote: null,
    promptEn: "Introduce one controlled geometric block to reinforce the visual hierarchy.",
    promptId: "Perkenalkan satu blok geometris yang terkendali untuk memperkuat hierarki visual."
  },
  {
    id: "organic-blob-accent",
    category: "expressive",
    name: "Organic blob accent",
    purpose: ["movement", "contrast"],
    compatibleMovements: ["contemporary-digital"],
    compatibleIndustries: [],
    incompatibleIndustries: [],
    suitableObjectives: [],
    minIntensity: "moderate",
    expressiveAudienceOnly: true,
    conflictsWithDenseCopy: false,
    reduceIfDenseImagery: false,
    requiresGrid: false,
    pairsWith: ["floating-element"],
    avoidWith: ["geometric-block-accent"],
    culturalNote: null,
    promptEn: "Add one soft, organic blob shape as a counterpoint to the composition's straight edges.",
    promptId: "Tambahkan satu bentuk blob organik yang lembut sebagai penyeimbang dari tepi-tepi lurus komposisi."
  },
  {
    id: "ribbon-band",
    category: "expressive",
    name: "Ribbon / banner band",
    purpose: ["emphasis", "information_grouping"],
    compatibleMovements: ["contemporary-digital", "editorial-modernism"],
    compatibleIndustries: [],
    incompatibleIndustries: [],
    suitableObjectives: ["promotion", "conversion", "launch", "event"],
    minIntensity: "moderate",
    expressiveAudienceOnly: false,
    conflictsWithDenseCopy: false,
    reduceIfDenseImagery: false,
    requiresGrid: false,
    pairsWith: ["label-tag"],
    avoidWith: [],
    culturalNote:
      "The band must read as an abstract graphic ribbon, not as a medal ribbon or heraldic device tied to a specific nation.",
    promptEn: "Carry the offer on a single graphic ribbon band rather than free-floating text.",
    promptId: "Tempatkan penawaran pada satu pita grafis (ribbon band), bukan teks yang mengambang bebas."
  },
  {
    id: "contour-line-mark",
    category: "expressive",
    name: "Contour line mark",
    purpose: ["rhythm", "movement"],
    compatibleMovements: ["contemporary-digital", "editorial-modernism"],
    compatibleIndustries: [],
    incompatibleIndustries: [],
    suitableObjectives: [],
    minIntensity: "expressive",
    expressiveAudienceOnly: false,
    conflictsWithDenseCopy: false,
    reduceIfDenseImagery: true,
    requiresGrid: false,
    pairsWith: [],
    avoidWith: [],
    culturalNote: null,
    promptEn: "Trace one continuous contour line to guide the eye across the composition.",
    promptId: "Gambarkan satu garis kontur menerus untuk menuntun mata melintasi komposisi."
  },
  {
    id: "abstract-graphic-mark",
    category: "expressive",
    name: "Abstract graphic mark",
    purpose: ["emphasis", "narrative"],
    compatibleMovements: ["contemporary-digital", "bauhaus"],
    compatibleIndustries: [],
    incompatibleIndustries: [],
    suitableObjectives: [],
    minIntensity: "moderate",
    expressiveAudienceOnly: false,
    conflictsWithDenseCopy: false,
    reduceIfDenseImagery: false,
    requiresGrid: false,
    pairsWith: [],
    avoidWith: [],
    culturalNote:
      "The mark must be invented for this composition and stay abstract — it must never resolve into a flag, crest, religious symbol or national emblem.",
    promptEn: "Place one invented abstract mark that carries the concept without becoming a literal symbol.",
    promptId: "Tempatkan satu tanda grafis abstrak yang dirancang khusus, tanpa menjadi simbol literal."
  },
  {
    id: "bold-graphic-symbol",
    category: "expressive",
    name: "Bold graphic symbol",
    purpose: ["emphasis", "narrative"],
    compatibleMovements: ["contemporary-digital", "brutalism"],
    compatibleIndustries: [],
    incompatibleIndustries: [],
    suitableObjectives: ["launch", "awareness", "brand-building"],
    minIntensity: "expressive",
    expressiveAudienceOnly: false,
    conflictsWithDenseCopy: false,
    reduceIfDenseImagery: false,
    requiresGrid: false,
    pairsWith: [],
    avoidWith: [],
    culturalNote:
      "The symbol must remain abstract and original to this brand — it must never resolve into a flag, religious mark or national emblem.",
    promptEn: "Use one bold, high-contrast graphic symbol as a single point of visual signature.",
    promptId: "Gunakan satu simbol grafis yang tebal dan berkontras tinggi sebagai satu tanda visual yang khas."
  },

  // --- Image treatments (doctrine §3.C) --------------------------------------
  {
    id: "selective-image-masking",
    category: "image_treatment",
    name: "Selective image masking",
    purpose: ["image_integration", "framing"],
    compatibleMovements: ["contemporary-digital", "editorial-modernism"],
    compatibleIndustries: [],
    incompatibleIndustries: [],
    suitableObjectives: [],
    minIntensity: "moderate",
    expressiveAudienceOnly: false,
    conflictsWithDenseCopy: false,
    reduceIfDenseImagery: false,
    requiresGrid: false,
    pairsWith: ["cropped-image-window"],
    avoidWith: [],
    culturalNote: null,
    promptEn: "Mask the image selectively against the grid instead of showing a full uncropped rectangle.",
    promptId: "Masking gambar secara selektif terhadap grid, alih-alih menampilkan persegi penuh tanpa crop."
  },
  {
    id: "cutout-silhouette",
    category: "image_treatment",
    name: "Cut-out image silhouette",
    purpose: ["image_integration", "emphasis"],
    compatibleMovements: ["contemporary-digital", "brutalism"],
    compatibleIndustries: [],
    incompatibleIndustries: [],
    suitableObjectives: [],
    minIntensity: "expressive",
    expressiveAudienceOnly: false,
    conflictsWithDenseCopy: false,
    reduceIfDenseImagery: false,
    requiresGrid: false,
    pairsWith: ["halftone-texture"],
    avoidWith: [],
    culturalNote: null,
    promptEn: "Cut the subject out of its background so it sits directly on the composition as a silhouette.",
    promptId: "Potong subjek dari latarnya sehingga tampil langsung di atas komposisi sebagai siluet cut-out."
  },
  {
    id: "duotone-image-treatment",
    category: "image_treatment",
    name: "Duotone image treatment",
    purpose: ["contrast", "image_integration"],
    compatibleMovements: ["swiss-international", "editorial-modernism", "minimalism"],
    compatibleIndustries: [],
    incompatibleIndustries: [],
    suitableObjectives: [],
    minIntensity: "moderate",
    expressiveAudienceOnly: false,
    conflictsWithDenseCopy: false,
    reduceIfDenseImagery: false,
    requiresGrid: false,
    pairsWith: ["selective-image-masking"],
    avoidWith: ["monochrome-image-treatment"],
    culturalNote: null,
    promptEn: "Render the photography in a duotone treatment drawn from the palette rather than full colour.",
    promptId: "Render fotografi dalam olahan duotone yang diambil dari palet, bukan warna penuh."
  },
  {
    id: "monochrome-image-treatment",
    category: "image_treatment",
    name: "Monochrome image treatment",
    purpose: ["contrast", "image_integration"],
    compatibleMovements: ["minimalism", "swiss-international", "brutalism"],
    compatibleIndustries: [],
    incompatibleIndustries: [],
    suitableObjectives: [],
    minIntensity: "moderate",
    expressiveAudienceOnly: false,
    conflictsWithDenseCopy: false,
    reduceIfDenseImagery: false,
    requiresGrid: false,
    pairsWith: ["cutout-silhouette"],
    avoidWith: ["duotone-image-treatment"],
    culturalNote: null,
    promptEn: "Render the photography in monochrome so colour is carried by type and accent alone.",
    promptId: "Render fotografi secara monokrom sehingga warna hanya dibawa oleh tipografi dan aksen."
  },

  // --- Typography treatments (doctrine §3.C) ---------------------------------
  {
    id: "oversized-cropped-headline",
    category: "typography_treatment",
    name: "Oversized, cropped headline",
    purpose: ["emphasis", "hierarchy"],
    compatibleMovements: ["brutalism", "bauhaus", "contemporary-digital"],
    compatibleIndustries: [],
    incompatibleIndustries: [],
    suitableObjectives: [],
    minIntensity: "moderate",
    expressiveAudienceOnly: false,
    conflictsWithDenseCopy: true,
    reduceIfDenseImagery: false,
    requiresGrid: false,
    pairsWith: ["cropped-image-window", "modular-grid-blocks"],
    avoidWith: ["stacked-typography-block"],
    culturalNote: null,
    promptEn: "Set the headline at an oversized scale, cropped by the frame edge, as the composition's dominant mass.",
    promptId: "Atur headline pada skala yang oversized, terpotong oleh tepi bidang, sebagai massa dominan komposisi."
  },
  {
    id: "cropped-bleeding-typography",
    category: "typography_treatment",
    name: "Cropped, bleeding typography",
    purpose: ["emphasis", "image_integration"],
    compatibleMovements: ["brutalism", "editorial-modernism"],
    compatibleIndustries: [],
    incompatibleIndustries: [],
    suitableObjectives: [],
    minIntensity: "expressive",
    expressiveAudienceOnly: false,
    conflictsWithDenseCopy: true,
    reduceIfDenseImagery: false,
    requiresGrid: false,
    pairsWith: ["cropped-image-window"],
    avoidWith: [],
    culturalNote: null,
    promptEn: "Let the headline bleed past the frame edge instead of resolving safely inside the margin.",
    promptId: "Biarkan headline meluber (bleed) melewati tepi bidang, alih-alih berhenti aman di dalam margin."
  },
  {
    id: "outlined-type-treatment",
    category: "typography_treatment",
    name: "Outlined type treatment",
    purpose: ["contrast", "emphasis"],
    compatibleMovements: ["contemporary-digital", "bauhaus"],
    compatibleIndustries: [],
    incompatibleIndustries: [],
    suitableObjectives: [],
    minIntensity: "moderate",
    expressiveAudienceOnly: false,
    conflictsWithDenseCopy: false,
    reduceIfDenseImagery: false,
    requiresGrid: false,
    pairsWith: [],
    avoidWith: [],
    culturalNote: null,
    promptEn: "Render the headline in outline (stroke-only) type so it reads as a graphic mark, not filled text.",
    promptId: "Render headline sebagai tipografi outline (stroke saja) sehingga terbaca sebagai tanda grafis, bukan teks solid."
  },
  {
    id: "stacked-typography-block",
    category: "typography_treatment",
    name: "Stacked typography block",
    purpose: ["hierarchy", "rhythm"],
    compatibleMovements: ["swiss-international", "bauhaus", "editorial-modernism"],
    compatibleIndustries: [],
    incompatibleIndustries: [],
    suitableObjectives: [],
    minIntensity: "minimal",
    expressiveAudienceOnly: false,
    conflictsWithDenseCopy: false,
    reduceIfDenseImagery: false,
    requiresGrid: false,
    pairsWith: ["column-system"],
    avoidWith: ["oversized-cropped-headline"],
    culturalNote: null,
    promptEn: "Stack the headline into a tight typographic block that reads as one shape before it reads as words.",
    promptId: "Susun headline menjadi satu blok tipografi yang rapat, terbaca sebagai satu bentuk sebelum terbaca sebagai kata."
  },
  {
    id: "type-crossing-image-boundary",
    category: "typography_treatment",
    name: "Type crossing the image boundary",
    purpose: ["image_integration", "typography_integration"],
    compatibleMovements: ["editorial-modernism", "contemporary-digital", "brutalism"],
    compatibleIndustries: [],
    incompatibleIndustries: [],
    suitableObjectives: [],
    minIntensity: "expressive",
    expressiveAudienceOnly: false,
    conflictsWithDenseCopy: true,
    reduceIfDenseImagery: false,
    requiresGrid: false,
    pairsWith: ["cropped-image-window", "grid-crossing-image"],
    avoidWith: [],
    culturalNote: null,
    promptEn: "Let the headline cross the boundary between the image and its background field.",
    promptId: "Biarkan headline melintasi batas antara gambar dan bidang latarnya."
  },

  // --- Texture (doctrine §4) --------------------------------------------------
  {
    id: "paper-grain-texture",
    category: "texture",
    name: "Paper grain texture",
    purpose: ["contrast"],
    compatibleMovements: ["editorial-modernism", "minimalism"],
    compatibleIndustries: [],
    incompatibleIndustries: [],
    suitableObjectives: [],
    minIntensity: "expressive",
    expressiveAudienceOnly: false,
    conflictsWithDenseCopy: false,
    reduceIfDenseImagery: true,
    requiresGrid: false,
    pairsWith: [],
    avoidWith: [],
    culturalNote: null,
    promptEn: "Add a subtle paper-grain surface texture across the composition.",
    promptId: "Tambahkan tekstur permukaan paper-grain yang halus pada seluruh komposisi."
  },
  {
    id: "film-grain-texture",
    category: "texture",
    name: "Film grain texture",
    purpose: ["contrast", "narrative"],
    compatibleMovements: ["editorial-modernism", "contemporary-digital"],
    compatibleIndustries: [],
    incompatibleIndustries: [],
    suitableObjectives: [],
    minIntensity: "expressive",
    expressiveAudienceOnly: false,
    conflictsWithDenseCopy: false,
    reduceIfDenseImagery: true,
    requiresGrid: false,
    pairsWith: [],
    avoidWith: ["photocopy-texture"],
    culturalNote: null,
    promptEn: "Apply a light film-grain texture over the photography for tactile, analogue contrast.",
    promptId: "Terapkan tekstur film-grain yang ringan pada fotografi untuk kontras taktil bergaya analog."
  },
  {
    id: "halftone-texture",
    category: "texture",
    name: "Halftone texture",
    purpose: ["contrast", "narrative"],
    compatibleMovements: ["brutalism", "contemporary-digital"],
    compatibleIndustries: [],
    incompatibleIndustries: [],
    suitableObjectives: [],
    minIntensity: "expressive",
    expressiveAudienceOnly: false,
    conflictsWithDenseCopy: false,
    reduceIfDenseImagery: true,
    requiresGrid: false,
    pairsWith: ["cutout-silhouette", "monochrome-image-treatment"],
    avoidWith: ["photocopy-texture"],
    culturalNote: null,
    promptEn: "Break part of the image into a halftone dot pattern for graphic, printed contrast.",
    promptId: "Pecah sebagian gambar menjadi pola dot halftone untuk kontras grafis bergaya cetak."
  },
  {
    id: "photocopy-texture",
    category: "texture",
    name: "Photocopy / print-noise texture",
    purpose: ["contrast", "narrative"],
    compatibleMovements: ["brutalism"],
    compatibleIndustries: [],
    incompatibleIndustries: [],
    suitableObjectives: [],
    minIntensity: "experimental",
    expressiveAudienceOnly: false,
    conflictsWithDenseCopy: false,
    reduceIfDenseImagery: true,
    requiresGrid: false,
    pairsWith: [],
    avoidWith: ["halftone-texture", "film-grain-texture"],
    culturalNote: null,
    promptEn: "Degrade part of the composition with a raw photocopy / print-noise texture.",
    promptId: "Degradasikan sebagian komposisi dengan tekstur photocopy / print-noise yang mentah."
  },

  // --- Pattern (doctrine §4) --------------------------------------------------
  {
    id: "dot-pattern",
    category: "pattern",
    name: "Dot pattern",
    purpose: ["rhythm", "information_grouping"],
    compatibleMovements: ["bauhaus", "contemporary-digital"],
    compatibleIndustries: [],
    incompatibleIndustries: [],
    suitableObjectives: [],
    minIntensity: "expressive",
    expressiveAudienceOnly: false,
    conflictsWithDenseCopy: false,
    reduceIfDenseImagery: true,
    requiresGrid: false,
    pairsWith: [],
    avoidWith: ["checker-pattern"],
    culturalNote: null,
    promptEn: "Use a repeated dot pattern as a background rhythm, kept subordinate to the main composition.",
    promptId: "Gunakan pola dot berulang sebagai ritme latar, tetap berada di bawah komposisi utama."
  },
  {
    id: "stripe-pattern",
    category: "pattern",
    name: "Stripe pattern",
    purpose: ["rhythm"],
    compatibleMovements: ["swiss-international", "bauhaus"],
    compatibleIndustries: [],
    incompatibleIndustries: [],
    suitableObjectives: [],
    minIntensity: "expressive",
    expressiveAudienceOnly: false,
    conflictsWithDenseCopy: false,
    reduceIfDenseImagery: true,
    requiresGrid: false,
    pairsWith: [],
    avoidWith: ["checker-pattern"],
    culturalNote: null,
    promptEn: "Use a disciplined stripe pattern to reinforce the grid's own rhythm.",
    promptId: "Gunakan pola garis-garis (stripe) yang disiplin untuk memperkuat ritme grid itu sendiri."
  },
  {
    id: "checker-pattern",
    category: "pattern",
    name: "Checker pattern",
    purpose: ["rhythm", "contrast"],
    compatibleMovements: ["bauhaus", "contemporary-digital"],
    compatibleIndustries: [],
    incompatibleIndustries: [],
    suitableObjectives: [],
    minIntensity: "experimental",
    expressiveAudienceOnly: false,
    conflictsWithDenseCopy: false,
    reduceIfDenseImagery: true,
    requiresGrid: false,
    pairsWith: [],
    avoidWith: ["dot-pattern", "stripe-pattern"],
    culturalNote: null,
    promptEn: "Use a bold checker pattern as a contained background field, never behind required text.",
    promptId: "Gunakan pola checker yang tegas sebagai bidang latar yang terkendali, jangan di belakang teks wajib."
  },
  {
    id: "modular-repetition-pattern",
    category: "pattern",
    name: "Modular repetition",
    purpose: ["rhythm", "hierarchy"],
    compatibleMovements: ["swiss-international", "bauhaus"],
    compatibleIndustries: [],
    incompatibleIndustries: [],
    suitableObjectives: [],
    minIntensity: "expressive",
    expressiveAudienceOnly: false,
    conflictsWithDenseCopy: false,
    reduceIfDenseImagery: true,
    requiresGrid: true,
    pairsWith: ["modular-grid-blocks"],
    avoidWith: [],
    culturalNote: null,
    promptEn: "Repeat one modular unit across the grid to build rhythm without adding new shapes.",
    promptId: "Ulangi satu unit modular di sepanjang grid untuk membangun ritme tanpa menambah bentuk baru."
  },

  // --- Layering (doctrine §4) --------------------------------------------------
  {
    id: "foreground-overlap",
    category: "layering",
    name: "Foreground overlap",
    purpose: ["movement", "emphasis"],
    compatibleMovements: ["contemporary-digital", "brutalism"],
    compatibleIndustries: [],
    incompatibleIndustries: [],
    suitableObjectives: [],
    minIntensity: "expressive",
    expressiveAudienceOnly: false,
    conflictsWithDenseCopy: false,
    reduceIfDenseImagery: false,
    requiresGrid: false,
    pairsWith: ["floating-element"],
    avoidWith: [],
    culturalNote: null,
    promptEn: "Let one element overlap the foreground so the composition reads in front-to-back depth.",
    promptId: "Biarkan satu elemen tumpang tindih di foreground agar komposisi terbaca dengan kedalaman depan-belakang."
  },
  {
    id: "background-layer-depth",
    category: "layering",
    name: "Background layer depth",
    purpose: ["framing", "narrative"],
    compatibleMovements: ["contemporary-digital", "editorial-modernism"],
    compatibleIndustries: [],
    incompatibleIndustries: [],
    suitableObjectives: [],
    minIntensity: "expressive",
    expressiveAudienceOnly: false,
    conflictsWithDenseCopy: false,
    reduceIfDenseImagery: true,
    requiresGrid: false,
    pairsWith: [],
    avoidWith: [],
    culturalNote: null,
    promptEn: "Set a quiet secondary layer behind the main subject to add depth without competing for attention.",
    promptId: "Letakkan satu lapisan sekunder yang tenang di belakang subjek utama untuk menambah kedalaman tanpa bersaing perhatian."
  },
  {
    id: "floating-element",
    category: "layering",
    name: "Floating element",
    purpose: ["emphasis", "movement"],
    compatibleMovements: ["contemporary-digital"],
    compatibleIndustries: [],
    incompatibleIndustries: [],
    suitableObjectives: [],
    minIntensity: "experimental",
    expressiveAudienceOnly: true,
    conflictsWithDenseCopy: false,
    reduceIfDenseImagery: false,
    requiresGrid: false,
    pairsWith: ["foreground-overlap", "organic-blob-accent"],
    avoidWith: [],
    culturalNote: null,
    promptEn: "Let one small element float free of the grid to add a single point of visual movement.",
    promptId: "Biarkan satu elemen kecil melayang bebas dari grid untuk menambah satu titik gerak visual."
  },
  {
    id: "grid-crossing-image",
    category: "layering",
    name: "Image crossing the grid boundary",
    purpose: ["image_integration", "movement"],
    compatibleMovements: ["brutalism", "contemporary-digital", "bauhaus"],
    compatibleIndustries: [],
    incompatibleIndustries: [],
    suitableObjectives: [],
    minIntensity: "expressive",
    expressiveAudienceOnly: false,
    conflictsWithDenseCopy: false,
    reduceIfDenseImagery: false,
    requiresGrid: true,
    pairsWith: ["modular-grid-blocks", "type-crossing-image-boundary"],
    avoidWith: [],
    culturalNote: null,
    promptEn: "Let the image cross a grid boundary rather than staying fully contained in one cell.",
    promptId: "Biarkan gambar melintasi batas grid, bukan sepenuhnya diam di dalam satu sel."
  },

  // --- Graphic accents (doctrine §4) -------------------------------------------
  {
    id: "label-tag",
    category: "accent",
    name: "Label / tag",
    purpose: ["information_grouping", "hierarchy"],
    compatibleMovements: ["swiss-international", "editorial-modernism", "contemporary-digital"],
    compatibleIndustries: [],
    incompatibleIndustries: [],
    suitableObjectives: ["promotion", "conversion", "consideration", "education"],
    minIntensity: "moderate",
    expressiveAudienceOnly: false,
    conflictsWithDenseCopy: false,
    reduceIfDenseImagery: false,
    requiresGrid: false,
    pairsWith: ["rule-divider"],
    avoidWith: [],
    culturalNote: null,
    promptEn: "Carry the offer or price as a single, clearly bounded label rather than free-floating type.",
    promptId: "Tempatkan penawaran atau harga sebagai satu label yang jelas batasnya, bukan teks yang mengambang bebas."
  },
  {
    id: "icon-marker",
    category: "accent",
    name: "Icon marker",
    purpose: ["information_grouping", "hierarchy"],
    compatibleMovements: ["swiss-international", "contemporary-digital"],
    compatibleIndustries: [],
    incompatibleIndustries: [],
    suitableObjectives: [],
    minIntensity: "moderate",
    expressiveAudienceOnly: false,
    conflictsWithDenseCopy: false,
    reduceIfDenseImagery: false,
    requiresGrid: false,
    pairsWith: [],
    avoidWith: [],
    culturalNote: null,
    promptEn: "Use one small icon marker to identify a supporting fact, not as decoration.",
    promptId: "Gunakan satu penanda ikon kecil untuk menandai satu fakta pendukung, bukan sebagai dekorasi."
  },
  {
    id: "annotation-caption",
    category: "accent",
    name: "Annotation / caption",
    purpose: ["information_grouping", "narrative"],
    compatibleMovements: ["editorial-modernism", "swiss-international"],
    compatibleIndustries: [],
    incompatibleIndustries: [],
    suitableObjectives: ["education", "consideration", "trust"],
    minIntensity: "moderate",
    expressiveAudienceOnly: false,
    conflictsWithDenseCopy: false,
    reduceIfDenseImagery: false,
    requiresGrid: false,
    pairsWith: [],
    avoidWith: [],
    culturalNote: null,
    promptEn: "Add one small caption-style annotation that grounds the image in a specific fact.",
    promptId: "Tambahkan satu anotasi bergaya caption yang menjangkarkan gambar pada satu fakta spesifik."
  },
  {
    id: "badge-mark",
    category: "accent",
    name: "Badge mark",
    purpose: ["emphasis", "information_grouping"],
    compatibleMovements: ["contemporary-digital"],
    compatibleIndustries: [],
    incompatibleIndustries: [],
    suitableObjectives: ["promotion", "launch", "event"],
    minIntensity: "moderate",
    expressiveAudienceOnly: true,
    conflictsWithDenseCopy: false,
    reduceIfDenseImagery: false,
    requiresGrid: false,
    pairsWith: ["ribbon-band"],
    avoidWith: [],
    culturalNote:
      "Keep the badge an abstract graphic mark — not a national emblem, religious symbol or official seal.",
    promptEn: "Place one badge mark to call out a single promotional fact, kept graphic rather than literal.",
    promptId: "Tempatkan satu badge untuk menyorot satu fakta promosi, tetap bersifat grafis, bukan literal."
  },
  {
    id: "stamp-mark",
    category: "accent",
    name: "Stamp mark",
    purpose: ["narrative", "emphasis"],
    compatibleMovements: ["contemporary-digital", "editorial-modernism"],
    compatibleIndustries: [],
    incompatibleIndustries: [],
    suitableObjectives: ["launch", "event", "brand-building"],
    minIntensity: "expressive",
    expressiveAudienceOnly: true,
    conflictsWithDenseCopy: false,
    reduceIfDenseImagery: false,
    requiresGrid: false,
    pairsWith: [],
    avoidWith: [],
    culturalNote:
      "Keep the stamp abstract and graphic — a seal, wax-stamp or postal-mark motif reads as a specific national or ceremonial symbol in several country DNAs and must not be rendered literally.",
    promptEn: "Add one stamp-like mark as a graphic signature, abstract rather than a literal seal.",
    promptId: "Tambahkan satu tanda bergaya stamp sebagai tanda tangan grafis, abstrak dan bukan cap literal."
  }
] as const;
