import type {
  DkvDerivation,
  Resolution,
  ScoredCandidate
} from "../../types/schemas/direction.schema";
import { labelOf } from "../dkv/doctrine";
import { round } from "../dkv/params";
import { RESOLUTION_TOLERANCE } from "../dkv/rules";

/**
 * Explainability (P1 spec §14).
 *
 * Every sentence here is assembled from a structured value that already
 * exists. Nothing is generated by a language model and nothing is written by
 * hand per case — which means an explanation can never drift away from the
 * arithmetic it claims to describe.
 */

/** Dimensions worth naming in prose, in the order a designer would argue them. */
const HEADLINE_DIMENSIONS = [
  "industry_fit",
  "communication_fit",
  "audience_fit",
  "culture_fit",
  "brand_fit"
] as const;

const humanise = (dimension: string): string => dimension.replace(/_/g, " ");

/** WHY was this movement and layout selected? */
export function explainSelection(
  selected: ScoredCandidate,
  runnerUp: ScoredCandidate | null
): string {
  const strengths = [...selected.score_breakdown]
    .filter((entry) => entry.applicable && HEADLINE_DIMENSIONS.includes(entry.dimension as never))
    .sort((a, b) => b.raw - a.raw)
    .slice(0, 3)
    .map((entry) => `${humanise(entry.dimension)} ${round(entry.raw)}`);

  const margin = runnerUp
    ? ` It beat ${runnerUp.candidate.movement_name} on ${runnerUp.candidate.layout_name} by ${round(selected.total_score - runnerUp.total_score)}.`
    : " It was the only candidate that survived filtering.";

  return `${selected.candidate.movement_name} on a ${selected.candidate.layout_name} layout scored ${round(selected.total_score)}, led by ${strengths.join(", ")}.${margin}`;
}

/** WHY did this candidate lose? */
export function explainRejection(candidate: ScoredCandidate, reason: string): string {
  return `${candidate.candidate.movement_name} on ${candidate.candidate.layout_name} (score ${round(candidate.total_score)}) was rejected: ${reason}`;
}

/** WHY was whitespace increased? WHY was a movement reduced? */
export function explainParameter(derivation: DkvDerivation): string {
  const moved = Math.abs(derivation.final - derivation.weighted_target) > RESOLUTION_TOLERANCE;
  const direction = derivation.final > derivation.weighted_target ? "raised" : "lowered";

  if (!moved) {
    const top = [...derivation.contributors].sort((a, b) => b.authority - a.authority)[0];
    return top
      ? `${derivation.param} settled at ${derivation.final}, driven mainly by ${labelOf(top.rank)} asking for ${top.value}.`
      : `${derivation.param} stayed at its default of ${derivation.base}; no layer expressed an opinion.`;
  }

  return `${derivation.param} was ${direction} from ${derivation.weighted_target} to ${derivation.final} because ${labelOf(
    rankOfLayer(derivation.governing_layer)
  )} holds it inside [${derivation.clamped_to.min}, ${derivation.clamped_to.max}].`;
}

/** WHY was a conflict resolved this way? */
export function explainResolution(resolution: Resolution): string {
  return `${resolution.rule}: ${resolution.param} moved from ${resolution.requested} to ${resolution.resolved} (${resolution.action}). ${resolution.reason}`;
}

const LAYER_RANKS: Record<string, number> = {
  communication_objective: 1,
  audience: 2,
  industry_requirements: 3,
  brand_identity: 4,
  dkv_fundamentals: 5,
  platform_constraints: 6,
  country_visual_dna: 7,
  design_movement: 8,
  contemporary_trends: 9,
  decorative_treatment: 10
};

const rankOfLayer = (layer: string): number => LAYER_RANKS[layer] ?? 10;

/**
 * The direction's full rationale.
 *
 * Ordered the way a design review runs: what was chosen, what it cost, what
 * moved, and what the data would not allow.
 */
export function buildRationale(input: {
  readonly selected: ScoredCandidate;
  readonly runnerUp: ScoredCandidate | null;
  readonly rejections: readonly string[];
  readonly resolutions: readonly Resolution[];
  readonly derivations: readonly DkvDerivation[];
  readonly relaxations: readonly string[];
}): string[] {
  const lines: string[] = [explainSelection(input.selected, input.runnerUp)];

  for (const rejection of input.rejections) lines.push(rejection);
  for (const resolution of input.resolutions) lines.push(explainResolution(resolution));

  // Only parameters that actually moved are worth a sentence.
  const moved = input.derivations.filter(
    (derivation) =>
      Math.abs(derivation.final - derivation.weighted_target) > RESOLUTION_TOLERANCE ||
      Math.abs(derivation.final - derivation.base) > 0.15
  );
  for (const derivation of moved) lines.push(explainParameter(derivation));

  for (const relaxation of input.relaxations) lines.push(relaxation);

  const failed = input.selected.failed_rules.slice(0, 3);
  for (const rule of failed) {
    lines.push(`Known weakness (${humanise(rule.dimension)}): ${rule.detail}`);
  }

  return lines;
}
